//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DidarApiWrapper.me.didar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBizDomainData", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class GetBizDomainData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.CallResponse ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.BizDomainData DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DidarApiWrapper.me.didar.CallResponse Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DidarApiWrapper.me.didar.BizDomainData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponse", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class CallResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DidarApiWrapper.me.didar.Status StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DidarApiWrapper.me.didar.Status StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizDomainData", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class BizDomainData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private System.Guid OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        private int CurrenCreditField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CurrenCredit {
            get {
                return this.CurrenCreditField;
            }
            set {
                if ((this.CurrenCreditField.Equals(value) != true)) {
                    this.CurrenCreditField = value;
                    this.RaisePropertyChanged("CurrenCredit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://didar.me/")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidApiKey = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersData", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class GetUsersData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.CallResponse ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.BizDomainUser[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DidarApiWrapper.me.didar.CallResponse Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DidarApiWrapper.me.didar.BizDomainUser[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizDomainUser", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class BizDomainUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContactsData", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class GetContactsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.CallResponse ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.Contact[] DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DidarApiWrapper.me.didar.CallResponse Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DidarApiWrapper.me.didar.Contact[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://didar.me/")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        private System.Guid OwnerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPhoneExtensionField;
        
        private bool IsDeletedField;
        
        private bool IsVIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactStatusField;
        
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DidarApiWrapper.me.didar.ArrayOfString OtherPhonesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string WorkPhone {
            get {
                return this.WorkPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPhoneField, value) != true)) {
                    this.WorkPhoneField = value;
                    this.RaisePropertyChanged("WorkPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string WorkPhoneExtension {
            get {
                return this.WorkPhoneExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPhoneExtensionField, value) != true)) {
                    this.WorkPhoneExtensionField = value;
                    this.RaisePropertyChanged("WorkPhoneExtension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool IsVIP {
            get {
                return this.IsVIPField;
            }
            set {
                if ((this.IsVIPField.Equals(value) != true)) {
                    this.IsVIPField = value;
                    this.RaisePropertyChanged("IsVIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ContactStatus {
            get {
                return this.ContactStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactStatusField, value) != true)) {
                    this.ContactStatusField = value;
                    this.RaisePropertyChanged("ContactStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public DidarApiWrapper.me.didar.ArrayOfString OtherPhones {
            get {
                return this.OtherPhonesField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherPhonesField, value) != true)) {
                    this.OtherPhonesField = value;
                    this.RaisePropertyChanged("OtherPhones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://didar.me/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://didar.me/", ConfigurationName="me.didar.CollaborativeSoap")]
    public interface CollaborativeSoap {
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://didar.me/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/GetBizDomain", ReplyAction="*")]
        DidarApiWrapper.me.didar.GetBizDomainResponse GetBizDomain(DidarApiWrapper.me.didar.GetBizDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/GetBizDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetBizDomainResponse> GetBizDomainAsync(DidarApiWrapper.me.didar.GetBizDomainRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://didar.me/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/GetUsers", ReplyAction="*")]
        DidarApiWrapper.me.didar.GetUsersResponse GetUsers(DidarApiWrapper.me.didar.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetUsersResponse> GetUsersAsync(DidarApiWrapper.me.didar.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://didar.me/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/GetContacts", ReplyAction="*")]
        DidarApiWrapper.me.didar.GetContactsResponse GetContacts(DidarApiWrapper.me.didar.GetContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/GetContacts", ReplyAction="*")]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetContactsResponse> GetContactsAsync(DidarApiWrapper.me.didar.GetContactsRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://didar.me/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/AddContact", ReplyAction="*")]
        DidarApiWrapper.me.didar.AddContactResponse AddContact(DidarApiWrapper.me.didar.AddContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://didar.me/AddContact", ReplyAction="*")]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.AddContactResponse> AddContactAsync(DidarApiWrapper.me.didar.AddContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBizDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBizDomain", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.GetBizDomainRequestBody Body;
        
        public GetBizDomainRequest() {
        }
        
        public GetBizDomainRequest(DidarApiWrapper.me.didar.GetBizDomainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class GetBizDomainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetBizDomainRequestBody() {
        }
        
        public GetBizDomainRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBizDomainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBizDomainResponse", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.GetBizDomainResponseBody Body;
        
        public GetBizDomainResponse() {
        }
        
        public GetBizDomainResponse(DidarApiWrapper.me.didar.GetBizDomainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class GetBizDomainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DidarApiWrapper.me.didar.GetBizDomainData GetBizDomainResult;
        
        public GetBizDomainResponseBody() {
        }
        
        public GetBizDomainResponseBody(DidarApiWrapper.me.didar.GetBizDomainData GetBizDomainResult) {
            this.GetBizDomainResult = GetBizDomainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(DidarApiWrapper.me.didar.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class GetUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetUsersRequestBody() {
        }
        
        public GetUsersRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(DidarApiWrapper.me.didar.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DidarApiWrapper.me.didar.GetUsersData GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(DidarApiWrapper.me.didar.GetUsersData GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContacts", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.GetContactsRequestBody Body;
        
        public GetContactsRequest() {
        }
        
        public GetContactsRequest(DidarApiWrapper.me.didar.GetContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class GetContactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime lastModifiedFrom;
        
        public GetContactsRequestBody() {
        }
        
        public GetContactsRequestBody(string apiKey, System.DateTime lastModifiedFrom) {
            this.apiKey = apiKey;
            this.lastModifiedFrom = lastModifiedFrom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactsResponse", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.GetContactsResponseBody Body;
        
        public GetContactsResponse() {
        }
        
        public GetContactsResponse(DidarApiWrapper.me.didar.GetContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class GetContactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DidarApiWrapper.me.didar.GetContactsData GetContactsResult;
        
        public GetContactsResponseBody() {
        }
        
        public GetContactsResponseBody(DidarApiWrapper.me.didar.GetContactsData GetContactsResult) {
            this.GetContactsResult = GetContactsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContact", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.AddContactRequestBody Body;
        
        public AddContactRequest() {
        }
        
        public AddContactRequest(DidarApiWrapper.me.didar.AddContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class AddContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DidarApiWrapper.me.didar.Contact contactData;
        
        public AddContactRequestBody() {
        }
        
        public AddContactRequestBody(string apiKey, DidarApiWrapper.me.didar.Contact contactData) {
            this.apiKey = apiKey;
            this.contactData = contactData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContactResponse", Namespace="http://didar.me/", Order=0)]
        public DidarApiWrapper.me.didar.AddContactResponseBody Body;
        
        public AddContactResponse() {
        }
        
        public AddContactResponse(DidarApiWrapper.me.didar.AddContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://didar.me/")]
    public partial class AddContactResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DidarApiWrapper.me.didar.GetContactsData AddContactResult;
        
        public AddContactResponseBody() {
        }
        
        public AddContactResponseBody(DidarApiWrapper.me.didar.GetContactsData AddContactResult) {
            this.AddContactResult = AddContactResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CollaborativeSoapChannel : DidarApiWrapper.me.didar.CollaborativeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollaborativeSoapClient : System.ServiceModel.ClientBase<DidarApiWrapper.me.didar.CollaborativeSoap>, DidarApiWrapper.me.didar.CollaborativeSoap {
        
        public CollaborativeSoapClient() {
        }
        
        public CollaborativeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollaborativeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollaborativeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollaborativeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DidarApiWrapper.me.didar.GetBizDomainResponse DidarApiWrapper.me.didar.CollaborativeSoap.GetBizDomain(DidarApiWrapper.me.didar.GetBizDomainRequest request) {
            return base.Channel.GetBizDomain(request);
        }
        
        public DidarApiWrapper.me.didar.GetBizDomainData GetBizDomain(string apiKey) {
            DidarApiWrapper.me.didar.GetBizDomainRequest inValue = new DidarApiWrapper.me.didar.GetBizDomainRequest();
            inValue.Body = new DidarApiWrapper.me.didar.GetBizDomainRequestBody();
            inValue.Body.apiKey = apiKey;
            DidarApiWrapper.me.didar.GetBizDomainResponse retVal = ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).GetBizDomain(inValue);
            return retVal.Body.GetBizDomainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetBizDomainResponse> DidarApiWrapper.me.didar.CollaborativeSoap.GetBizDomainAsync(DidarApiWrapper.me.didar.GetBizDomainRequest request) {
            return base.Channel.GetBizDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetBizDomainResponse> GetBizDomainAsync(string apiKey) {
            DidarApiWrapper.me.didar.GetBizDomainRequest inValue = new DidarApiWrapper.me.didar.GetBizDomainRequest();
            inValue.Body = new DidarApiWrapper.me.didar.GetBizDomainRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).GetBizDomainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DidarApiWrapper.me.didar.GetUsersResponse DidarApiWrapper.me.didar.CollaborativeSoap.GetUsers(DidarApiWrapper.me.didar.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public DidarApiWrapper.me.didar.GetUsersData GetUsers(string apiKey) {
            DidarApiWrapper.me.didar.GetUsersRequest inValue = new DidarApiWrapper.me.didar.GetUsersRequest();
            inValue.Body = new DidarApiWrapper.me.didar.GetUsersRequestBody();
            inValue.Body.apiKey = apiKey;
            DidarApiWrapper.me.didar.GetUsersResponse retVal = ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetUsersResponse> DidarApiWrapper.me.didar.CollaborativeSoap.GetUsersAsync(DidarApiWrapper.me.didar.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetUsersResponse> GetUsersAsync(string apiKey) {
            DidarApiWrapper.me.didar.GetUsersRequest inValue = new DidarApiWrapper.me.didar.GetUsersRequest();
            inValue.Body = new DidarApiWrapper.me.didar.GetUsersRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DidarApiWrapper.me.didar.GetContactsResponse DidarApiWrapper.me.didar.CollaborativeSoap.GetContacts(DidarApiWrapper.me.didar.GetContactsRequest request) {
            return base.Channel.GetContacts(request);
        }
        
        public DidarApiWrapper.me.didar.GetContactsData GetContacts(string apiKey, System.DateTime lastModifiedFrom) {
            DidarApiWrapper.me.didar.GetContactsRequest inValue = new DidarApiWrapper.me.didar.GetContactsRequest();
            inValue.Body = new DidarApiWrapper.me.didar.GetContactsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.lastModifiedFrom = lastModifiedFrom;
            DidarApiWrapper.me.didar.GetContactsResponse retVal = ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).GetContacts(inValue);
            return retVal.Body.GetContactsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetContactsResponse> DidarApiWrapper.me.didar.CollaborativeSoap.GetContactsAsync(DidarApiWrapper.me.didar.GetContactsRequest request) {
            return base.Channel.GetContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DidarApiWrapper.me.didar.GetContactsResponse> GetContactsAsync(string apiKey, System.DateTime lastModifiedFrom) {
            DidarApiWrapper.me.didar.GetContactsRequest inValue = new DidarApiWrapper.me.didar.GetContactsRequest();
            inValue.Body = new DidarApiWrapper.me.didar.GetContactsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.lastModifiedFrom = lastModifiedFrom;
            return ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).GetContactsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DidarApiWrapper.me.didar.AddContactResponse DidarApiWrapper.me.didar.CollaborativeSoap.AddContact(DidarApiWrapper.me.didar.AddContactRequest request) {
            return base.Channel.AddContact(request);
        }
        
        public DidarApiWrapper.me.didar.GetContactsData AddContact(string apiKey, DidarApiWrapper.me.didar.Contact contactData) {
            DidarApiWrapper.me.didar.AddContactRequest inValue = new DidarApiWrapper.me.didar.AddContactRequest();
            inValue.Body = new DidarApiWrapper.me.didar.AddContactRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.contactData = contactData;
            DidarApiWrapper.me.didar.AddContactResponse retVal = ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).AddContact(inValue);
            return retVal.Body.AddContactResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DidarApiWrapper.me.didar.AddContactResponse> DidarApiWrapper.me.didar.CollaborativeSoap.AddContactAsync(DidarApiWrapper.me.didar.AddContactRequest request) {
            return base.Channel.AddContactAsync(request);
        }
        
        public System.Threading.Tasks.Task<DidarApiWrapper.me.didar.AddContactResponse> AddContactAsync(string apiKey, DidarApiWrapper.me.didar.Contact contactData) {
            DidarApiWrapper.me.didar.AddContactRequest inValue = new DidarApiWrapper.me.didar.AddContactRequest();
            inValue.Body = new DidarApiWrapper.me.didar.AddContactRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.contactData = contactData;
            return ((DidarApiWrapper.me.didar.CollaborativeSoap)(this)).AddContactAsync(inValue);
        }
    }
}
